name: build and run tests
# https://github.com/avsm/setup-ocaml

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-version:
          - 4.12.0
          - 4.07.1
          # - 4.09.1
          # - 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache # https://github.com/marketplace/actions/cache
        uses: actions/cache@v2.0.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.opam
            _opam
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-new-${{ hashFiles('goblint.opam.locked') }}

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      # Split build and tests into separate jobs and let build job upload the goblint binary as an artifact?
      # https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow

      - name: Setup goblint (dependencies, build)
        run: bash -x scripts/travis-ci.sh

      - name: Run regression tests
        run: ./make.sh headers testci

      - name: Run octapron regression tests # skipped by default but CI has apron, so explicitly test group (which ignores skipping -- it's now a feature!)
        run: ruby scripts/update_suite.rb group octapron -s

      - name: Run domain tests
        run: |
          ./make.sh domaintest
          ./goblint.domaintest

      - name: Test Marshaling
        run: |
          ./make.sh
          ruby scripts/update_suite.rb -m
